CREATE DATABASE IF NOT EXISTS users_api;

CREATE TABLE users(
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(12) NOT NULL
);
